//! Arko LCAx writer — emits a Project/Assembly/Product/EPD-shaped
//! [LCAx](https://docs.lcax.org) v3.4 document from an Arko `Study`
//! plus its `Computed` result.
//!
//! # Why LCAx
//!
//! The Phase-1 plan referenced "EPDX" as the digital-EPD bullet. As of
//! 2024-08-22 that name was archived by its authors
//! (<https://github.com/ocni-dtu/epdx>) in favour of **LCAx**, the
//! actively maintained successor (`lcax_models` v3.x on crates.io,
//! Apache-2.0). LCAx is the modern open exchange format for LCA
//! results, EPDs, and assemblies, maintained by Christian Kongsgaard
//! and Andreas Sørensen (Arkitema + Ramboll). Closing the bullet via
//! LCAx is not a compromise — it is the correct updated target.
//!
//! Full rationale: see `DECISIONS.md` entry `D-0018`.
//!
//! # Scope (V1)
//!
//! - **Direction: writer only.** Reading existing LCAx documents into
//!   Arko Studies is a future-V2 ingestion concern; V1's job is to make
//!   "import data → build study → run calculation → export EPD"
//!   demonstrable end-to-end with a real schema-conformant artifact.
//! - **Document shape: full minimum-viable nesting.** LCAx's root type
//!   is `Project`; standalone Product/EPD documents are not allowed by
//!   the schema. V1 emits a synthetic single-Assembly / single-Product
//!   `Project` wrapping the EPD that holds Arko's `Computed.impact`
//!   vector. The wrapper is real but thin.
//! - **Stage assignment: everything in `a1a3`.** Arko's `Study` does
//!   not yet model life-cycle stages (cradle-to-gate/grave/etc.); a
//!   single number per category is what the engine produces today.
//!   `a1a3` (cradle-to-gate) is the truthful default for unit-process
//!   LCAs that don't include downstream stages, which is what Arko's
//!   carpet-smoke and beef-multi-process fixtures actually represent.
//!   Real stage decomposition is a Phase-2/3 question — see
//!   `DECISIONS.md` D-0018.
//! - **`standard` enum mapping: derived from `Study.method`.** LCAx
//!   constrains `EPD.standard` to `EN15804A1 | EN15804A2 | UNKNOWN`.
//!   Arko's preset registry currently ships four methods, only one of
//!   which (`ef-3.1`) is EN 15804+A2-aligned by construction. The
//!   other three (AR6 GWP100, AR5 GWP100, CML-IA baseline) emit as
//!   `UNKNOWN` — *not* because the method is unknown but because the
//!   schema's enum lacks a matching variant. The actual method id is
//!   preserved in the EPD's `comment` field
//!   (`"Generated by Arko using method <id>@<version>"`) so downstream
//!   consumers can identify the methodology even when `standard` is
//!   `UNKNOWN`. See refinement #2 in D-0018 for the design rationale.
//!
//! # EPD-domain metadata
//!
//! LCAx requires ~10 EPD-domain fields the engine doesn't model
//! (`reference_service_life`, `published_date`, `valid_until`,
//! `version`, `declared_unit`, `subtype`, `location`, `project_phase`,
//! `software_info`, `format_version`). [`EpdDocumentMetadata`] carries
//! these as a single config struct passed to the writer.
//!
//! The struct is named `EpdDocumentMetadata` rather than `WriterConfig`
//! deliberately: in Phase 2 the same shape will feed an ILCD+EPD
//! writer (the actual Environdec submission format), so the metadata
//! is intended as a portable EPD-domain concept, not LCAx-specific
//! config.
//!
//! # API
//!
//! ```ignore
//! use arko_io_lcax::{write_lcax_project, EpdDocumentMetadata};
//!
//! let metadata = EpdDocumentMetadata::with_product_name("Carpet, 1 m²");
//! let project = write_lcax_project(&study, &computed, &metadata)?;
//! let json = serde_json::to_string_pretty(&project)?;
//! ```
//!
//! # License posture
//!
//! `lcax_models` is Apache-2.0 (see <https://github.com/ocni-dtu/lcax>).
//! No dataset attribution plumbing is required — LCAx is a *format* +
//! *library*, not an LCI dataset. The crates.io "non-standard" license
//! classifier on the lcax/lcax_models crates is a packaging-convention
//! quirk (Cargo.toml uses `license-file` instead of
//! `license = "Apache-2.0"`); the LICENSE file in the repository is
//! plain Apache-2.0 with no carve-outs.

pub mod error;
pub mod metadata;
pub mod writer;

pub use error::WriteError;
pub use metadata::EpdDocumentMetadata;
pub use writer::write_lcax_project;
