//! The LCAx writer itself — `Study + Computed + EpdDocumentMetadata`
//! → `lcax_models::project::Project`.
//!
//! The writer is **pure** (no I/O): it builds an in-memory `Project`
//! that callers serialise via `serde_json` (or whatever encoder they
//! prefer). Keeping I/O at the call site means tests don't touch the
//! filesystem and the writer composes cleanly with the WASM/Python
//! bindings the upstream `lcax` umbrella crate already ships.
//!
//! # Mapping decisions (V1)
//!
//! | Concern | Decision | Why |
//! |---|---|---|
//! | Project nesting | Synthetic 1×1×1 (one Assembly, one Product, one EPD) | Schema requires Project root; no standalone Product/EPD shape exists. |
//! | Stage assignment | All impact values land at `LifeCycleModule::A1A3` | Arko produces one number per category (no stage breakdown); A1A3 (cradle-to-gate) is truthful for the unit-process inputs Arko fixtures actually represent. Stage decomposition is Phase 2-3. |
//! | `Standard` enum | `ef-3.1` → `EN15804A2`; everything else → `UNKNOWN` | LCAx constrains `EPD.standard` to those three variants. CML-IA / IPCC presets predate or sit outside EN 15804 and emit as `UNKNOWN`. |
//! | Method preservation | `EPD.comment` carries `"Generated by Arko using method <id>@<version>"` | When `standard` is `UNKNOWN`, the actual methodology stays discoverable. Without this, downstream consumers couldn't tell whether `UNKNOWN` meant CML-IA, AR6, AR5, or "we don't know." |
//! | Indicator key map | Strict mapping in [`map_impact_id_to_key`]; unknown ids surface as `WriteError::UnknownImpactId` | Silent drops would emit a *valid-looking* EPD with missing indicators, which is the worst kind of correctness failure. |

use arko_core::pipeline::Computed;
use arko_core::study::Study;
use lcax_core::country::Country;
use lcax_models::assembly::{Assembly, AssemblyReference};
use lcax_models::epd::{EPDReference, Standard, SubType, EPD};
use lcax_models::life_cycle_base::{
    ImpactCategory, ImpactCategoryKey, Impacts, LifeCycleModule,
};
use lcax_models::product::{ImpactData, Product, ProductReference};
use lcax_models::project::{Location, Project, ProjectPhase, SoftwareInfo};
use lcax_models::shared::Unit;

use crate::error::WriteError;
use crate::metadata::{
    EpdDocumentMetadata, EpdSubtype, ProjectPhase as ArkoProjectPhase,
};

/// Build a schema-conformant LCAx [`Project`] from an Arko `Study` plus
/// its computed impacts.
///
/// See module-level docs for the full mapping rationale. The returned
/// `Project` is ready to serialise via `serde_json::to_string`;
/// validation against the LCAx JSON schema is the upstream library's
/// job (see <https://docs.lcax.org/concept/data-structure>).
pub fn write_lcax_project(
    study: &Study,
    computed: &Computed,
    metadata: &EpdDocumentMetadata,
) -> Result<Project, WriteError> {
    if computed.impact.len() != study.impacts.len() {
        return Err(WriteError::ImpactVectorShapeMismatch {
            impact_len: computed.impact.len(),
            meta_len: study.impacts.len(),
        });
    }

    let impacts = build_impacts(study, computed)?;
    let standard = standard_from_method_id(&study.method.id);
    let comment = format!(
        "Generated by Arko using method {}@{}",
        study.method.id, study.method.version
    );

    let location = Location {
        country: country_from_iso(&metadata.country_iso_alpha2),
        city: None,
        address: None,
    };

    let epd = EPD {
        id: format!("arko-epd-{}", metadata.product_name_slug()),
        name: metadata.product_name.clone(),
        declared_unit: Unit::PCS,
        version: metadata.document_version.clone(),
        published_date: metadata.published_date,
        valid_until: metadata.valid_until,
        source: None,
        reference_service_life: Some(metadata.reference_service_life_years),
        standard,
        comment: Some(comment),
        location: location.country.clone(),
        subtype: subtype_from_arko(metadata.subtype),
        conversions: None,
        impacts,
        meta_data: None,
    };

    let product = Product {
        id: format!("arko-product-{}", metadata.product_name_slug()),
        name: metadata.product_name.clone(),
        description: None,
        reference_service_life: metadata.reference_service_life_years,
        impact_data: vec![ImpactData::EPD(EPDReference::EPD(epd))],
        quantity: 1.0,
        unit: Unit::PCS,
        transport: None,
        results: None,
        meta_data: None,
    };

    let assembly = Assembly {
        id: format!("arko-assembly-{}", metadata.product_name_slug()),
        name: metadata.product_name.clone(),
        description: None,
        comment: None,
        quantity: 1.0,
        unit: Unit::PCS,
        classification: None,
        products: vec![ProductReference::Product(product)],
        results: None,
        meta_data: None,
    };

    let life_cycle_modules = vec![LifeCycleModule::A1A3];
    let impact_categories = study
        .impacts
        .iter()
        .map(|m| map_impact_id_to_key(&m.id))
        .collect::<Result<Vec<_>, _>>()?;

    Ok(Project {
        id: format!("arko-project-{}", metadata.product_name_slug()),
        name: metadata.product_name.clone(),
        description: None,
        comment: None,
        location,
        owner: None,
        format_version: env!("CARGO_PKG_VERSION").into(),
        lcia_method: Some(format!("{}@{}", study.method.id, study.method.version)),
        classification_systems: None,
        reference_study_period: None,
        life_cycle_modules,
        impact_categories,
        assemblies: vec![AssemblyReference::Assembly(assembly)],
        results: None,
        project_info: None,
        project_phase: project_phase_from_arko(metadata.project_phase),
        software_info: SoftwareInfo {
            lca_software: metadata.software_name.clone(),
            lca_software_version: metadata.software_version.clone(),
            goal_and_scope_definition: metadata.goal_and_scope.clone(),
            calculation_type: None,
        },
        meta_data: None,
    })
}

/// Build the `Impacts` keyed map from Arko's parallel `study.impacts`
/// (metadata) and `computed.impact` (numerical values) vectors.
///
/// Every category emits as a single-stage entry under
/// `LifeCycleModule::A1A3`. See module-docs for the V1 stage decision.
fn build_impacts(study: &Study, computed: &Computed) -> Result<Impacts, WriteError> {
    let mut out = Impacts::new();
    for (k, meta) in study.impacts.iter().enumerate() {
        let key = map_impact_id_to_key(&meta.id)?;
        let mut category = ImpactCategory::new();
        category.insert(LifeCycleModule::A1A3, Some(computed.impact[k]));
        out.insert(key, category);
    }
    Ok(out)
}

/// Map an Arko `ImpactMeta.id` to the corresponding LCAx
/// `ImpactCategoryKey` enum variant. Strict — unknown ids return an
/// error rather than silently dropping the indicator.
///
/// The mapping covers every category id present in the four Arko V1
/// preset methods (AR6 GWP100, AR5 GWP100, EF 3.1, CML-IA baseline 4.8).
/// New presets that introduce a new category id must extend this map.
pub fn map_impact_id_to_key(id: &str) -> Result<ImpactCategoryKey, WriteError> {
    Ok(match id {
        // Climate change — IPCC AR5/AR6/EF/CML all use one of these names.
        "gwp100" | "climate-change" => ImpactCategoryKey::GWP,
        "gwp100-fossil" | "climate-change-fossil" => ImpactCategoryKey::GWP_FOS,
        "gwp100-biogenic" | "climate-change-biogenic" => ImpactCategoryKey::GWP_BIO,
        "gwp100-luluc" | "climate-change-luluc" => ImpactCategoryKey::GWP_LUL,
        // EN 15804+A2 core emission indicators.
        "ozone-depletion" => ImpactCategoryKey::ODP,
        "acidification" => ImpactCategoryKey::AP,
        "photochemical-ozone-formation" => ImpactCategoryKey::POCP,
        // Eutrophication — split (EF 3.1) vs combined (CML).
        "eutrophication" => ImpactCategoryKey::EP,
        "eutrophication-freshwater" => ImpactCategoryKey::EP_FW,
        "eutrophication-marine" => ImpactCategoryKey::EP_MAR,
        "eutrophication-terrestrial" => ImpactCategoryKey::EP_TER,
        // Resource use (CML-IA baseline).
        "adp-elements" => ImpactCategoryKey::ADPE,
        "adp-fossil" => ImpactCategoryKey::ADPF,
        other => return Err(WriteError::UnknownImpactId(other.to_string())),
    })
}

/// `ef-3.1` → `EN15804A2`; everything else → `UNKNOWN`. See module docs
/// for why this is correct (schema constraint, not an admission of
/// ignorance about the actual methodology).
fn standard_from_method_id(id: &str) -> Standard {
    match id {
        "ef-3.1" => Standard::EN15804A2,
        _ => Standard::UNKNOWN,
    }
}

fn subtype_from_arko(s: EpdSubtype) -> SubType {
    match s {
        EpdSubtype::Generic => SubType::GENERIC,
        EpdSubtype::Specific => SubType::SPECIFIC,
        EpdSubtype::Industry => SubType::INDUSTRY,
        EpdSubtype::Representative => SubType::REPRESENTATIVE,
    }
}

fn project_phase_from_arko(p: ArkoProjectPhase) -> ProjectPhase {
    match p {
        ArkoProjectPhase::StrategicDesign => ProjectPhase::STRATEGIC_DESIGN,
        ArkoProjectPhase::ConceptDesign => ProjectPhase::CONCEPT_DESIGN,
        ArkoProjectPhase::TechnicalDesign => ProjectPhase::TECHNICAL_DESIGN,
        ArkoProjectPhase::Construction => ProjectPhase::CONSTRUCTION,
        ArkoProjectPhase::PostCompletion => ProjectPhase::POST_COMPLETION,
        ArkoProjectPhase::InUse => ProjectPhase::IN_USE,
        ArkoProjectPhase::Other => ProjectPhase::OTHER,
    }
}

/// Best-effort ISO-alpha-2 → `Country` enum lookup. LCAx's `Country`
/// derives from the standard ISO 3166-1 alpha-2 list; serde
/// deserialises the lowercase form, so we route through serde rather
/// than enumerating ~250 variants here. Unknown codes fall back to
/// `Country::default()` (typically the enum's first variant) — V1
/// callers who care should set `country_iso_alpha2` to a known value.
fn country_from_iso(iso: &str) -> Country {
    let lc = iso.to_ascii_lowercase();
    serde_json::from_value::<Country>(serde_json::Value::String(lc)).unwrap_or_default()
}

impl EpdDocumentMetadata {
    /// Slug a product name for use in synthetic ids (lowercase, ASCII,
    /// underscore-joined). Output is purely cosmetic — the schema
    /// requires `id` to be a string but does not constrain its format.
    pub(crate) fn product_name_slug(&self) -> String {
        self.product_name
            .chars()
            .map(|c| {
                if c.is_ascii_alphanumeric() {
                    c.to_ascii_lowercase()
                } else {
                    '_'
                }
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // `Standard`, `SubType`, `ImpactCategoryKey` etc. from lcax_models
    // don't `derive(Debug)`, so these tests use `matches!` + explicit
    // panics rather than `assert_eq!` (which requires Debug on both
    // sides for the failure-message formatter).

    #[test]
    fn standard_mapping_known_methods() {
        assert!(matches!(
            standard_from_method_id("ef-3.1"),
            Standard::EN15804A2
        ));
        assert!(matches!(
            standard_from_method_id("ipcc-ar6-gwp100"),
            Standard::UNKNOWN
        ));
        assert!(matches!(
            standard_from_method_id("ipcc-ar5-gwp100"),
            Standard::UNKNOWN
        ));
        assert!(matches!(
            standard_from_method_id("cml-ia-baseline"),
            Standard::UNKNOWN
        ));
    }

    #[test]
    fn impact_id_map_covers_v1_presets() {
        // AR6/AR5
        assert!(matches!(
            map_impact_id_to_key("gwp100").unwrap(),
            ImpactCategoryKey::GWP
        ));
        // EF 3.1
        assert!(matches!(
            map_impact_id_to_key("climate-change").unwrap(),
            ImpactCategoryKey::GWP
        ));
        assert!(matches!(
            map_impact_id_to_key("ozone-depletion").unwrap(),
            ImpactCategoryKey::ODP
        ));
        assert!(matches!(
            map_impact_id_to_key("acidification").unwrap(),
            ImpactCategoryKey::AP
        ));
        assert!(matches!(
            map_impact_id_to_key("photochemical-ozone-formation").unwrap(),
            ImpactCategoryKey::POCP
        ));
        assert!(matches!(
            map_impact_id_to_key("eutrophication-freshwater").unwrap(),
            ImpactCategoryKey::EP_FW
        ));
        assert!(matches!(
            map_impact_id_to_key("eutrophication-marine").unwrap(),
            ImpactCategoryKey::EP_MAR
        ));
        assert!(matches!(
            map_impact_id_to_key("eutrophication-terrestrial").unwrap(),
            ImpactCategoryKey::EP_TER
        ));
        // CML-IA combined EP + ADP
        assert!(matches!(
            map_impact_id_to_key("eutrophication").unwrap(),
            ImpactCategoryKey::EP
        ));
        assert!(matches!(
            map_impact_id_to_key("adp-elements").unwrap(),
            ImpactCategoryKey::ADPE
        ));
        assert!(matches!(
            map_impact_id_to_key("adp-fossil").unwrap(),
            ImpactCategoryKey::ADPF
        ));
    }

    #[test]
    fn unknown_impact_id_errors_explicitly() {
        let err = map_impact_id_to_key("made-up-category").unwrap_err();
        match err {
            WriteError::UnknownImpactId(id) => assert_eq!(id, "made-up-category"),
            other => panic!("expected UnknownImpactId, got {other:?}"),
        }
    }

    #[test]
    fn product_name_slug_lowercases_and_replaces_punctuation() {
        let m = EpdDocumentMetadata::with_product_name("Carpet, 1 m²");
        let slug = m.product_name_slug();
        // Spaces, commas, and non-ASCII (²) all collapse to underscores.
        assert!(slug.starts_with("carpet"));
        assert!(slug.contains('_'));
        assert!(!slug.chars().any(char::is_uppercase));
    }
}
